fix(snap): Fix build failure on armhf/riscv64 platforms
The cffi dependency wheel requires libffi development headers to be installed on these platforms:

```text
::             running build_ext
::             building '_cffi_backend' extension
::             arm-linux-gnueabihf-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/build/project-initializer/parts/project-initializer/install/include -I/usr/include/python3.12 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-312/src/c/_cffi_backend.o
::             src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
::                15 | #include <ffi.h>
::                   |          ^~~~~~~
::             compilation terminated.
::             error: Command '['arm-linux-gnueabihf-gcc', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-g', '-O2', '-Wall', '-fPIC', '-DFFI_BUILDING=1', '-DUSE__THREAD', '-DHAVE_SYNC_SYNCHRONIZE', '-I/usr/include/ffi', '-I/usr/include/libffi', '-I/build/project-initializer/parts/project-initializer/install/include', '-I/usr/include/python3.12', '-c', 'src/c/_cffi_backend.c', '-o', 'build/temp.linux-armv7l-cpython-312/src/c/_cffi_backend.o']' returned non-zero exit status 1.
```

This patch fixes the problem by adding libffi-dev to the build-packages, which will provide the necessary files to build the wheel.

Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>